name: test-livedata

on:
  pull_request:
    paths:
      - livedata/**
      - devenv.nix
      - devenv.lock
      - .github/workflows/test-livedata.yml
      - .github/workflows/elixir-test.yml

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/elixir-test.yml
    with:
      target_folder: livedata
