name: test-livedata

on:
  pull_request:
    paths:
      - livedata/**
      - devenv.nix
      - devenv.lock
      - .github/workflows/test-livedata.yml
      - .github/actions/elixir-test/**
  merge_group:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/elixir-test
        with:
          target_folder: livedata
